# Always validate the PR title, and ignore the commits
titleOnly: true

# See: https://github.com/commitizen/conventional-commit-types/blob/v2.2.0/index.json
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert