env:
- GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- id: mailchain-darwin-amd64
  ldflags: -s -w -X github.com/mailchain/mailchain.Version={{.Version}} -X github.com/mailchain/mailchain.BuildDate={{.Date}} -X github.com/mailchain/mailchain.CommitHash={{ .ShortCommit }}
  binary: mailchain
  env:
  - CGO_ENABLED=1  
  - CC=o64-clang 
  - CXX=o64-clang++
  main: ./cmd/mailchain/main.go 
  goos:
    - darwin
  goarch:
    - amd64
- id: mailchain-linux-amd64
  ldflags: -s -w -X github.com/mailchain/mailchain.Version={{.Version}} -X github.com/mailchain/mailchain.BuildDate={{.Date}} -X github.com/mailchain/mailchain.CommitHash={{ .ShortCommit }}
  binary: mailchain
  env:
  - CGO_ENABLED=1
  main: ./cmd/mailchain/main.go
  goos:
    - linux
  goarch:
    - amd64 
- id: indexer-linux-amd64
  ldflags: -s -w -X github.com/mailchain/mailchain.Version={{.Version}} -X github.com/mailchain/mailchain.BuildDate={{.Date}} -X github.com/mailchain/mailchain.CommitHash={{ .ShortCommit }}
  binary: indexer
  env:
  - CGO_ENABLED=0
  main: ./cmd/indexer/main.go
  goos:
    - linux
  goarch:
    - amd64     
- id: mailchain-windows-amd64
  ldflags: -s -w -X github.com/mailchain/mailchain.Version={{.Version}} -X github.com/mailchain/mailchain.BuildDate={{.Date}} -X github.com/mailchain/mailchain.CommitHash={{ .ShortCommit }}
  binary: mailchain
  env:
    - CGO_ENABLED=1
    - CC=x86_64-w64-mingw32-gcc
    - CXX=x86_64-w64-mingw32-g++
  main: ./cmd/mailchain/main.go
  goos:
    - windows
  goarch:
    - amd64  
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
    files:
    - Readme.MD
    - LICENSE   
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^dev:'
    - 'README'    
    - Merge pull request
    - Merge branch    
brew:
  github:
    owner: mailchain
    name: homebrew-tap
  folder: Formula
  homepage: https://mailchain.xyz
  description: Secure, email-like messaging for blockchain addresses and accounts
  test: |
    system "#{bin}/mailchain -v"
scoop:
  bucket:
    owner: mailchain
    name: scoop-bucket
  homepage: https://mailchain.xyz
  description: Secure, email-like messaging for blockchain addresses and accounts
  license: MIT
dockers:
  -     
    binaries: # Name templates of the built binaries that should be used.
    - indexer
    goos: linux # GOOS of the built binary that should be used. 
    goarch: amd64 # GOARCH of the built binary that should be used.
    dockerfile: ./cmd/indexer/Dockerfile    
    
    image_templates:
    - "mailchain/indexer:latest"
    - "mailchain/indexer:v{{.Version}}"
    
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}/indexer"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=repository=https://github.com/mailchain/mailchain"
    - "--label=homepage=https://mailchain.xyz"
