version: "3.7"

services:
    indexer-substrate:
        environment:
            INDEXER_RPC_ADDRESS: ws://localnode:9944
            INDEXER_NETWORK: edgeware-local
        depends_on:
            - localnode
    localnode:
        image: mailchain/edgeware-node:v3.0.8
        volumes:
            - edgeware_data:/root/.local/share        
        ports:
            - "9944:9944"
        entrypoint:
            [
                "edgeware",
                "--dev",
                "--rpc-external",
                "--ws-external"
            ]
volumes:
    edgeware_data: