version: "3.7"

services:
    indexer-substrate:
        image: mailchain/indexer
        entrypoint:
            [
                "/indexer",
                "substrate",
                "--start-block=latest",
                "--postgres-host=database",
                "--envelope-postgres-password=envelope",
                "--indexer-postgres-password=indexer",
                "--pubkey-postgres-password=pubkey",
                "--raw-store-path=./tmp/tx",
            ]
        depends_on:
            - database
