version: '3.7'

services: 
    db:
        image: postgres
        environment: 
            - POSTGRES_USER=mailchain
            - POSTGRES_PASSWORD=mailchain
        ports: 
            - 5432:5432
        volumes: 
            - db_data:/var/lib/postgresql/data

volumes: 
    db_data:
